apiVersion: v1
kind: Service
metadata:
  name: dummy-django-app
  labels:
    app: dummy-django
spec:
  type: NodePort
  selector:
    app: dummy-django
  ports:
    - port: 8000
      targetPort: 8000