apiVersion: v1
kind: Service
metadata:
  name: dummy-flask-service
spec:
  selector:
    app: dummy-flask
  ports:
  - protocol: "TCP"
    port: 5000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-flask
spec:
  selector:
    matchLabels:
      app: dummy-flask
  replicas: 4
  template:
    metadata:
      labels:
        app: dummy-flask
    spec:
      containers:
      - name: dummy-flask
        image: dummy-flask:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000